### ISSUE TITLE
error comparing raw data zips

### ISSUE THREAD

**Issue by RGreinacher** [Dalphi/dalphi#192]
Randomized with seed 53104

RawData sends a zip archive containing all raw data
     Failure/Error: expect(response.body).to eq(File.read(file.path))

```
   expected: "PK\u0003\u0004\u0014\u0000\u0000\b\b\u0000\x8Cb\u001EI\xB1\x81\x87gq\u0002\u0000\u0000\u0016\u0005\u...6\u0000\u0000\u0000\u0000\u0002\u0000\u0002\u0000k\u0000\u0000\u0000}\u0004\u0000\u0000\u0000\u0000"
        got: "PK\u0003\u0004\u0014\u0000\u0000\b\b\u0000\x8Db\u001EI\xB1\x81\x87gq\u0002\u0000\u0000\u0016\u0005\u...6\u0000\u0000\u0000\u0000\u0002\u0000\u0002\u0000k\u0000\u0000\u0000}\u0004\u0000\u0000\u0000\u0000"

   (compared using ==)

   Diff:

 # ./spec/requests/projects/raw_data/index_spec.rb:76:in `block (2 levels) in <top (required)>'
```
